### ISSUE TITLE
Inconsistent handling of input between event manager and function manager

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#270]
The simple ticker event driver pushes empty input to the event which is passed to the function via payload.  The payload passed to the function is sent as a string, whereas the function expects an object.

However, when calling a function directly via `dispatch exec` empty input is passed as an object to payload.  This seems inconsistent.

- [x] Bug
- [ ] Feature
- [ ] Enhancement

## Possible Implementation

Either an empty string or an object should be passed to the function in all situations (via event, direct function exec, or API gateway).  It should be consistent.

## Complexity

- [x] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [x] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
This issue is broader than initially thought, event manager passes payload as is when executing function: https://github.com/vmware/dispatch/blob/935adb9135a5f714dc1e4e2a0f85f0c64a4f9a52/pkg/event-manager/subscriptions/manager.go#L136 in every case. `data` is of type `string` whereas function manager always expects JSON object `map[string]interface{}`. This means that even when the event payload is JSON, it's still passed as a nested string (it's not unmarshalled correctly), and functions cannot use it directly (they would have to parse it first).

When thinking about this, I came up with following questions needing answers:
* Function Manager expects input in a certain format. This is fine if its API is only called either via CLI, or API Gateway/Event Manager - they can do the parsing/validation first. If we expose Function Manager API directly though, should we make it more tolerant WRT payload it accepts, to follow [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle)?  For example, if the user wants to invoke function directly, using Function Manager API (not CLI), and pass non-JSON payload, should we allow that. 
* Even if the payload is first validated/parsed by the intermediary service (like Event Manager), it may not be enough. For example, the CloudEvent spec does not specify the payload format, apart from saying that `content-type` attribute, if present, should indicate the type. `content-type` is not mandatory though. If `content-type` is set and is set to `application/json`, Event Manager can unmarshal the payload into JSON object and pass it to the function manager. What should happen if `content-type` is not set, or is set to something else?

My answer to both these questions would be:
Function Manager should accept non-JSON input, and pass the input as is by default. If binary data needs to be handled, input should be base64 encoded. An optional content-type can be specified. If content-type is set to `application/json`, it's automatically unmarshalled. 
For input schema validation to work, we could enforce `application/json` content-type (e.g. if input-schema is set, and content-type is not set/set to something else, throw an error).

CC @imikushin please share your view.

**Comment by tenczar** [comment]
Was there an offline discussion about Karol's proposal? I think his solution is certainly the most flexible and gives end users the most control.

**Comment by berndtj** [comment]
No, but I generally agree with it.  Just need to get @imikushin on board.

**Comment by kars7e** [comment]
Fixed in #458
