### ISSUE TITLE
Add Kubeless as FaaS driver

### ISSUE THREAD

**Issue by andresmgot** [vmware/dispatch#429]
### Detailed Description

As far as I understand, possible function drivers are OpenFaas, Openwhisk and riff. We would like to contribute with a Kubeless driver.

### Context

[Kubeless](https://github.com/kubeless/kubeless) is one important FaaS platform for Kubernetes so it would be a good fit for dispatch.

### Possible Implementation

There is not much documentation on how to implement a new FaaS driver so it would be great to have some help here.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [X] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by kars7e** [comment]
Hey @andresmgot, that would be awesome. Indeed we don't have any docs for adding new driver - I'd love to have this as an exercise to add some! Let me list the things that might be useful for you, and we can go from there.
* Currently, each functions driver lives in a separate directory within [`functions`](https://github.com/vmware/dispatch/tree/master/pkg/functions) folder (we had discussions about pulling them out into separate directory structure/repositories, but we don't have any concrete plans yet, so we can add kubeless there too).
* Each driver must implement [`FaaSDriver`](https://github.com/vmware/dispatch/blob/186129d49e735fbd5994ba995faded7bc343497b/pkg/functions/types.go#L61) interface. 
* There is a driver map which configures each driver in [`main.go` file](https://github.com/vmware/dispatch/blob/186129d49e735fbd5994ba995faded7bc343497b/cmd/function-manager/main.go#L38). This will be refactored, but don't worry about that.
* You can look at one of the existing drivers, e.g. [OpenFaaS](https://github.com/vmware/dispatch/blob/186129d49e735fbd5994ba995faded7bc343497b/pkg/functions/openfaas/driver.go), to get a general idea behind what driver usually does.
* Dispatch is installed via `dispatch install`, its code lives [here](https://github.com/vmware/dispatch/blob/186129d49e735fbd5994ba995faded7bc343497b/pkg/dispatchcli/cmd/install.go). It's a big file now, and we have to make it easier at some point. the general idea behind it is to manage installation of multiple helm charts. I see kubeless already has a chart, so that's great. We install Kafka by default, so you can use this instance in kubeless.  Dispatch install takes a `config.yml` file with installation details - you can find the default values for it [here](https://github.com/vmware/dispatch/blob/186129d49e735fbd5994ba995faded7bc343497b/pkg/dispatchcli/cmd/install_config.go).

Please let us know here what else would be useful.

**Comment by andresmgot** [comment]
Hi @kars7e, thanks for the pointers! I think that can be enough for getting started. I still have a question though. I see that by default OpenFaas is used for deploying/executing functions, isn't it?. How can that be configured?

**Comment by kars7e** [comment]
It's configured via `install.yaml`. If you set:
```yaml
dispatch:
  faas: riff
```
It will use riff Instead. You can find all the available flags and their default values in this file: https://github.com/vmware/dispatch/blob/186129d49e735fbd5994ba995faded7bc343497b/pkg/dispatchcli/cmd/install_config.go

**Comment by andresmgot** [comment]
Got it! Thank you.
